export const FETCH_ART_COLLECTION_START = "FETCH_ART_COLLECTION_START";
export const FETCH_ART_COLLECTION_SUCCESS = "FETCH_ART_COLLECTION_SUCCESS";
export const FETCH_ART_COLLECTION_FAIL = "FETCH_ART_COLLECTION_FAIL";

export const FILTER_ART_COLLECTION_START = " FILTER_ART_COLLECTION_START";
export const FILTER_ART_COLLECTION_SUCCESS = " FILTER_ART_COLLECTION_SUCCESS";
export const FILTER_ART_COLLECTION_FAIL = " FILTER_ART_COLLECTION_FAIL";

export const GET_ART_DETAILS_START = "GET_ART_DETAILS_START";
export const GET_ART_DETAILS_SUCCESS = "GET_ART_DETAILS_SUCCESS";
export const GET_ART_DETAILS_FAIL = "GET_ART_DETAILS_FAIL";